"""cycles updated schema

Revision ID: e943cccae0e9
Revises: 13ababff6f70
Create Date: 2026-07-09 12:17:18.177467

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e943cccae0e9"
down_revision: str | Sequence[str] | None = "13ababff6f70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("period_length_override", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "period_length_override")
    # ### end Alembic commands ###
